<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>14</LangVersion>
    <UserSecretsId>6963f896-189e-49e6-a482-f22fcf907387</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Aes256CryptoLib">
      <HintPath>..\..\toolkits\Aes256CryptoLib.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WouldYouRather.Application\WouldYouRather.Application.csproj" />
    <ProjectReference Include="..\WouldYouRather.Infrastructure\WouldYouRather.Infrastructure.csproj" />
  </ItemGroup>
</Project>
